/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package racing.arena.server;

public class App {
    public String getGreeting() {
        return "Hello World, this is server: " + Test.test;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
